### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/SpaceYaTechMentorship#1]
**Description**
We will be using React Router for our routing needs and we need to add it to our project. React router will allow us to move from one page to another seamlessly.

**Scenarios**
- A user needs to move from the signup page to the login page.
- A user needs to navigate from the login page to the dashboard page

**Tasks**
  - [ ] Connect the React Router to the react application
  - [ ] Provide a route for the login page
  - [ ] Provide a route for the signup page
  - [ ] A user can navigate between the 2 pages seamlessly
